name: "Release: 3. Build and Publish"
on:
  push:
    tags:
      - 'release-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Environment
        run: |
          php .github/release.php current >> $GITHUB_ENV

      - name: Fail if tag does not match VERSION file
        run: |
          if [[ "${{GITHUB_REF}}" != "refs/tags/release-${{ env.current_version }}" ]]; then
            echo "::error::This tag doesn't match the VERSION file"
            exit 1
          fi

      - name: Build TGZ
        run: |
          rm -rf .gitignore
          rm -rf .git
          rm -rf .github
          rm -rf .gitattributes
          rm -rf _test
          rm -f .editorconfig
          mkdir -p data/pages/playground
          echo "====== PlayGround ======" > data/pages/playground/playground.txt
          cd ..
          mv dokuwiki "dokuwiki-${{ env.current_version }}"
          tar -czvf "dokuwiki-${{ env.current_version }}.tgz" dokuwiki-${{ env.current_version }}
          rm -rf "dokuwiki-${{ env.current_version }}"
          mkdir dokuwiki
          mv "dokuwiki-${{ env.current_version }}.tgz" dokuwiki/

#      - name: Setup SSH Key
#        uses: shimataro/ssh-key-action@v2
#        with:
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          # generate with ssh-keyscan -H <server>
#          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
#
#      - name: Deploy to Server
#        run: |
#          scp "dokuwiki-${{ steps.get_version.outputs.VERSION }}.tgz" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:htdocs/src/dokuwiki/
#          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd htdocs/src/dokuwiki/ && tar -xzvf dokuwiki-${{ steps.get_version.outputs.VERSION }}.tgz"
